### ISSUE TITLE
Idea is very cool. Does this still works?

### ISSUE THREAD

**Issue by grepsuzette** [SmithChart/twitter-printer#1]
I am curious to know whether this still works.
It's a fantastic idea :)

**Comment by SmithChart** [comment]
Using this was really fun. During event we printed like hundreds of meters of paper. People would stop in front of the installation, tweet and be super happy to get it printed. Some event searched for tweets from hours ago :-)

Twitter has, as far as I know closed API access. Thus I guess it will not work anymore.

Feel free to grab the code and give it a try - or even make it work again.
I'll mark this repo as archived now. If I would want to use this in the future I would probably rewrite it for Mastodon as social network an use something like ``fpdf2`` to generate the prints.
